name: Check Daily Movies

on:
  schedule:
    # Cron roda em UTC. 12:00 UTC = 09:00 Brasil
    - cron: '0 12 * * *'
  workflow_dispatch: # Permite rodar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permissão necessária para fazer commit
    
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Requests
        run: pip install requests

      - name: Rodar Script
        env:
          WATCHMODE_API_KEY: ${{ secrets.WATCHMODE_API_KEY }}
        run: python main.py

      - name: Commit e Push do JSON
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data/releases.json
          # Só faz commit se houver mudanças
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update daily releases [skip ci]" && git push)
